name: data-factory-deploy
description: Deploy Azure Data Factory resources

inputs:
  resourceGroupName:
    description: 'Data Factory resource group name'
    required: true
  dataFactoryName:
    description: 'Data factory name'
    required: true
  armTemplateFile:
    description: 'ARM template file name'
    required: false
    default: 'ARMTemplateForFactory.json'
  armTemplateParametersFile:
    description: 'ARM template parameters file name'
    required: false
    default: 'ARMTemplateParametersForFactory.json'
  additionalParameters:
    description: 'Parameters which will be replaced in the ARM template'
    required: false
    default: ''
  azPSVersion:
    description: 'Parameters which skip the Az module installation'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Run Pre-Deployment Script
      uses: azure/powershell@v2
      with:
        failOnStandardError: true
        azPSVersion: ${{ inputs.azPSVersion }}
        inlineScript: |
          ${{ github.action_path }}/PrePostDeploymentScript.ps1 `
              -ArmTemplate "${{ inputs.armTemplateFile }}" `
              -ResourceGroupName "${{ inputs.resourceGroupName }}" `
              -DataFactoryName "${{ inputs.dataFactoryName }}" `
              -PreDeployment $true `
              -DeleteDeployment $false

    # - name: Run Pre-Deployment Script
    #   uses: azure/powershell@v2
    #   with:
    #     failOnStandardError: true
    #     azPSVersion: ${{ inputs.azPSVersion }}
    #     inlineScript: |
    #       ${{ github.action_path }}/PrePostDeploymentScript.Ver2.ps1 `
    #           -ArmTemplate "${{ inputs.armTemplateFile }}" `
    #           -ResourceGroupName "${{ inputs.resourceGroupName }}" `
    #           -DataFactoryName "${{ inputs.dataFactoryName }}" `
    #           -PreDeployment $true `
    #           -DeleteDeployment $false `
    #           -ArmTemplateParameters "${{ inputs.armTemplateParametersFile }}"

    - name: Run ARM Deploy
      uses: azure/arm-deploy@v2
      with:
        resourceGroupName: ${{ inputs.resourceGroupName }}
        template: ${{ inputs.armTemplateFile }}
        parameters: ${{ inputs.armTemplateParametersFile }} factoryName=${{ inputs.dataFactoryName }} ${{ inputs.additionalParameters }}

    - name: Run Post-Deployment Script
      uses: azure/powershell@v2
      with:
        failOnStandardError: true
        azPSVersion: ${{ inputs.azPSVersion }}
        inlineScript: |
          ${{ github.action_path }}/PrePostDeploymentScript.ps1 `
              -ArmTemplate "${{ inputs.armTemplateFile }}" `
              -ResourceGroupName "${{ inputs.resourceGroupName }}" `
              -DataFactoryName "${{ inputs.dataFactoryName }}" `
              -PreDeployment $false `
              -DeleteDeployment $true

    # - name: Run Post-Deployment Script
    #   uses: azure/powershell@v2
    #   with:
    #     failOnStandardError: true
    #     azPSVersion: ${{ inputs.azPSVersion }}
    #     inlineScript: |
    #       ${{ github.action_path }}/PrePostDeploymentScript.Ver2.ps1 `
    #           -ArmTemplate "${{ inputs.armTemplateFile }}" `
    #           -ResourceGroupName "${{ inputs.resourceGroupName }}" `
    #           -DataFactoryName "${{ inputs.dataFactoryName }}" `
    #           -PreDeployment $false `
    #           -DeleteDeployment $true `
    #           -ArmTemplateParameters "${{ inputs.armTemplateParametersFile }}"
